export const imageExtensions: string[] = ['jpg', 'jpeg', 'png', 'gif', 'svg']
export const videoExtensions: string[] = ['mp4', 'webm', 'ogg']
export const textFileExtensions: string[] = [
    'txt',
    'html',
    'js',
    'json',
    'xml',
    "yml",
    "yaml",
    "php",
    "py",
    "java",
    "gitignore",
    "sh",
    "c",
    "cpp",
    "h",
    "cs",
    "css",
    "scss",
    "sass",
    "gitconfig",
    "md",
    "reg",
    "toml",
];